###
# docker-compose.yml for testing and experimentation
###

###
# Unidata Docker Tomcat
###

unidata-tomcat:
  image: ghcr.io/mcicolella/unidata-tomcat-docker:latest
  ports:
    - "80:8080"
  container_name: unidata-tomcat
  volumes:
    - ./logs/:/usr/local/tomcat/logs/
  env_file:
    - "compose.env"

